<a href="https://colab.research.google.com/github/GuillaumeArp/Wild_Notebooks/blob/main/Mathematics_rhymes_with_Numpy_part_1_Guillaume_Arp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mission 1

Find a way to calculate the following statistical indicators for any given one-dimensional array using NumPy functions, and use them on a array filled with 20 random floats.
- mode
- median
- average
- the range (the difference between max and min)
- standard deviation
- variance
- the different quantiles

Then, create another array with 20 random floats and calculate the Pearson coefficient between the two arrays.

In [1]:
import numpy as np

In [2]:
random_array = 100 * np.random.rand(20)
random_array

array([55.48902223,  9.96692722, 47.38541297, 97.60280867, 39.88894749,
       61.09677462, 95.71579561, 19.18185133, 24.2116472 , 89.90354774,
       81.2804758 , 31.87861222, 84.34370606, 87.46235719, 75.83945148,
       31.39918846, 98.40192554, 87.02421269, 53.37383054, 26.56201985])

In [3]:
# Mode

values, counts = np.unique(random_array, return_counts=True)
array_mode = values[np.argmax(counts)]
array_mode

9.966927221675181

In [4]:
# Median

np.median(random_array)

58.29289842451132

In [5]:
# Average

np.average(random_array)

59.90042574574856

In [6]:
np.ptp(random_array)

88.4349983175176

In [7]:
# Standard deviation

np.std(random_array)

28.849061051294036

In [8]:
# Variance

np.var(random_array)

832.2683235412906

In [9]:
# Quantiles

print(np.quantile(random_array, 0.25))
print(np.quantile(random_array, 0.5))
print(np.quantile(random_array, 0.75))

31.758756284048992
58.29289842451132
87.13374881626562


In [10]:
second_random_array = 100 * np.random.rand(20)

In [11]:
np.corrcoef(random_array, second_random_array)

array([[1.        , 0.08838866],
       [0.08838866, 1.        ]])

## Mission 2

Create a function using NumPy that indicates the values (integers only), from -100 to 100, where the remainder from performing Euclidean division by both 3 and 7 is equal.

In [21]:
def mod_3_and_7_equal():
  array_range = np.arange(-100, 101)
  result = np.where(array_range % 3 == array_range % 7)
  return array_range[result]

mod_3_and_7_equal()

array([-84, -83, -82, -63, -62, -61, -42, -41, -40, -21, -20, -19,   0,
         1,   2,  21,  22,  23,  42,  43,  44,  63,  64,  65,  84,  85,
        86])

## Mission 3

Create a function that returns the [inverse value (for `3`, return `1/3`)](https://en.wikipedia.org/wiki/Multiplicative_inverse) of a set of values contained in a NumPy array

In [13]:
def inverse_array(arr):
  result = []
  for i in arr:
    if i != 0:
      result.append(np.reciprocal(i))
    else:
      result.append(np.NaN)
  
  return np.array(result)

new_array = np.array([1, 0.5, 2, 0.33, 3, 9, 21, 0.25, 0.75, 0])

print(inverse_array(new_array))

[1.         2.         0.5        3.03030303 0.33333333 0.11111111
 0.04761905 4.         1.33333333        nan]
