<a href="https://colab.research.google.com/github/GuillaumeArp/Wild_Notebooks/blob/main/NumPy_Introduction_Guillaume_Arp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running
np.__version__

'1.19.5'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])

array_miss_2 = np.array([0.8, 0.6, 0.4])

array_miss_2


array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements, 
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])

def np_random_range():
  result_array = []
  while len(result_array) < 10:
    number = np.random.random()
    if number > 0.25:
      result_array.append(number)
      
  return np.array(result_array)
  
# Used a while loop to keep populating the list until there are 10 items,
# then converted the list into an array.

np_random_range()



array([0.76711632, 0.85715782, 0.78644501, 0.41918829, 0.46606166,
       0.83559134, 0.80341284, 0.54847952, 0.3747887 , 0.59874023])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

# numpy.empty() is used to initialize an array of the desired shape, and filled
# with random values.

np.empty(2)


array([2.0e-323, 2.5e-323])

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can chose the length of this array.

array_zeros = np.zeros((3, 3))

array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.

array_randint = np.random.randint(low=0, high=100, size=10)

array_randint

array([14,  5, 62, 20, 54,  1, 38, 60, 78, 50])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.

array_random_choice = np.random.choice(np.arange(0,8), size=50)

array_random_choice

array([6, 1, 1, 2, 3, 4, 6, 2, 1, 2, 2, 4, 3, 6, 1, 1, 3, 3, 4, 3, 5, 4,
       7, 6, 6, 1, 3, 4, 4, 0, 6, 0, 5, 3, 2, 4, 7, 0, 6, 7, 2, 4, 1, 6,
       4, 6, 3, 2, 1, 1])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6

array_randint[2:6]

array([62, 20, 54,  1])

In [ ]:
# Mission 9 : Use the `argmin()` method to return the index of the smallest element in the array from mission 6

array_min = np.argmin(array_randint)

print(f"Smallest element index in array_randint: {array_min}")

Smallest element index in array_randint: 5


In [ ]:
# Mission 10 : Using the `where()` method, return the indices of all the values in the array from mission 6 that are greater than their median value.

np.where(array_randint > np.median(array_randint))

(array([2, 4, 7, 8, 9]),)

In [ ]:
# Mission 11: Create 3 arrays filled with 5 random integers each, and place them in another array.
# You have now an array with (3, 5) shape. You can use the `shape` attribute to check it.
# Display the elements, with each column appearing on a different line (so there will be 5 lines with 3 values each)

temp_array_1 = np.random.randint(low=0, high=10, size=5)
temp_array_2 = np.random.randint(low=0, high=10, size=5)
temp_array_3 = np.random.randint(low=0, high=10, size=5)
full_array = np.array([temp_array_1, temp_array_2, temp_array_3])

In [ ]:
print(full_array.shape)
print(full_array)
print(full_array.transpose())

(3, 5)
[[8 7 5 4 3]
 [4 8 7 8 4]
 [6 3 8 8 8]]
[[8 4 6]
 [7 8 3]
 [5 7 8]
 [4 8 8]
 [3 4 8]]


In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that returns the smallest and largest value it contains, with their indexes!
# You are allowed to use `min()` and `max()` methods.
# Example with a shorter array: [300, 500, 1000, 700, 100, 600] -> (4, 100), (2, 1000)
# Example with a shorter array: [80, 50, 90, -20, 100, 10] -> (3, -20), (4, 100)

array_randfloat = 100 * np.random.rand(20)

def min_max_array(arr):
  min_value = min(arr)
  min_index = np.argmin(arr)
  max_value = max(arr)
  max_index = np.argmax(arr)
  return f"({min_index}, {min_value}), ({max_index}, {max_value})"

print(array_randfloat)
min_max_array(array_randfloat)

[49.36047644 85.95538444 83.75142023  8.2789777  96.17115733 70.18923889
 31.84758236 14.95945924 80.49854584 95.37517855 30.52855589 13.51524884
 24.40747838 10.83187761 42.40161143  9.77651724 51.68639239 48.50877863
 56.50902259 26.8204707 ]


'(3, 8.27897770125623), (4, 96.17115732812034)'

In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
# Create a function that will go through each array using a for loop.
# At each iteration of the loop the function should compare the values of the 2 arrays located at the same index position.
# Return all indices where the values of the 2 arrays happen to be equal, in a list.
# If no values are equal at the same indices across the 2 arrays, that list will be empty.
# Example with shorter arrays: [1, 3, 5, 7] & [2, 3, 5, 8] -> [1, 2]
# Example with shorter arrays: [1, 1, 1, 1] & [1, 2, 3, 4] -> [0]

randint_array_1 = np.random.randint(low=0, high=10, size=20)
randint_array_2 = np.random.randint(low=0, high=10, size=20)

def array_compare(arr1, arr2):
  comparison_list = []
  for i in range(len(arr1)):
    if arr1[i] == arr2[i]:
      comparison_list.append(i)

  return comparison_list

print(randint_array_1)
print(randint_array_2)
array_compare(randint_array_1, randint_array_2)


[4 2 3 8 4 4 3 0 0 6 3 3 9 0 5 8 6 6 4 1]
[6 2 4 3 3 4 0 6 5 1 7 3 7 4 8 4 1 1 6 8]


[1, 5, 11]

In [ ]:
# Mission 14: now, just compare both arrays of mission 13 with this command (change the name of arrays): array1 == array2

print(randint_array_1 == randint_array_2)

[False  True False False False  True False False False False False  True
 False False False False False False False False]
